blank_issues_enabled: false
contact_links:
    - name: 🔒 Report a Security Vulnerability
      url: https://github.com/humanwhocodes/humanfs/security/advisories/new
      about: Privately report a security vulnerability to the team
    - name: 🗣 Ask a Question, Discuss
      url: https://github.com/humanwhocodes/humanfs/discussions
      about: Get help using humanfs
